_schema: _schema
source: /src/
paths:
  uploads: public/uploads
  static: public
collections_config:
  blog:
    path: /src/blog
    glob:
      - blog
    name: Blog Files
    singular_name:
    icon: newspaper
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description: Are these the files?
    preview:
    sort:
    sort_options:
    _editables:
      text:
        allow_custom_markup: true
        remove_custom_markup: false
        bold:
        copyformatting:
        italic:
        link:
        paths:
        redo:
        removeformat:
        strike:
        subscript:
        superscript:
        underline:
        undo:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
collection_groups:
  - heading: blog
    collections:
      -
_enabled_editors:
  - content
timezone: America/New_York
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
